In [11]:
!pip install wfdb

Requirement already satisfied: wfdb in /usr/local/lib/python3.12/dist-packages (4.3.1)
Requirement already satisfied: aiohttp>=3.10.11 in /usr/local/lib/python3.12/dist-packages (from wfdb) (3.13.3)
Requirement already satisfied: fsspec>=2023.10.0 in /usr/local/lib/python3.12/dist-packages (from wfdb) (2025.3.0)
Requirement already satisfied: matplotlib>=3.2.2 in /usr/local/lib/python3.12/dist-packages (from wfdb) (3.10.0)
Requirement already satisfied: numpy>=1.26.4 in /usr/local/lib/python3.12/dist-packages (from wfdb) (2.0.2)
Requirement already satisfied: pandas>=2.2.3 in /usr/local/lib/python3.12/dist-packages (from wfdb) (3.0.2)
Requirement already satisfied: requests>=2.8.1 in /usr/local/lib/python3.12/dist-packages (from wfdb) (2.32.4)
Requirement already satisfied: scipy>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from wfdb) (1.16.3)
Requirement already satisfied: soundfile>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from wfdb) (0.13.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->wfdb) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->wfdb) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->wfdb) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->wfdb) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->wfdb) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->wfdb) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->wfdb) (1.23.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->wfdb) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->wfdb) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->wfdb) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->wfdb) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->wfdb) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->wfdb) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->wfdb) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->wfdb) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.8.1->wfdb) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.8.1->wfdb) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.8.1->wfdb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.8.1->wfdb) (2026.2.25)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from soundfile>=0.10.0->wfdb) (2.0.0)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp>=3.10.11->wfdb) (4.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->soundfile>=0.10.0->wfdb) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.2.2->wfdb) (1.17.0)

In [12]:
!git clone https://github.com/muha-0/beat-synchronous-tokenizer

fatal: destination path 'beat-synchronous-tokenizer' already exists and is not an empty directory.

In [13]:
%cd beat-synchronous-tokenizer
!ls

/content/beat-synchronous-tokenizer/beat-synchronous-tokenizer
beat-synchronous-tokenizer	ecg_ssl    train.py
checkpoints_fixed_ssl_rawpatch	notebooks

In [14]:
!mkdir -p physionet.org/files/ptb-xl/1.0.3
!wget -O physionet.org/files/ptb-xl/1.0.3/ptbxl_database.csv https://physionet.org/files/ptb-xl/1.0.3/ptbxl_database.csv
!wget -O physionet.org/files/ptb-xl/1.0.3/scp_statements.csv https://physionet.org/files/ptb-xl/1.0.3/scp_statements.csv

--2026-04-01 01:37:42--  https://physionet.org/files/ptb-xl/1.0.3/ptbxl_database.csv
Resolving physionet.org (physionet.org)... 18.18.42.54
Connecting to physionet.org (physionet.org)|18.18.42.54|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6594879 (6.3M) [text/plain]
Saving to: ‘physionet.org/files/ptb-xl/1.0.3/ptbxl_database.csv’

physionet.org/files 100%[===================>]   6.29M   243KB/s    in 26s

2026-04-01 01:38:09 (244 KB/s) - ‘physionet.org/files/ptb-xl/1.0.3/ptbxl_database.csv’ saved [6594879/6594879]

--2026-04-01 01:38:09--  https://physionet.org/files/ptb-xl/1.0.3/scp_statements.csv
Resolving physionet.org (physionet.org)... 18.18.42.54
Connecting to physionet.org (physionet.org)|18.18.42.54|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9720 (9.5K) [text/plain]
Saving to: ‘physionet.org/files/ptb-xl/1.0.3/scp_statements.csv’

physionet.org/files 100%[===================>]   9.49K  --.-KB/s    in 0s

2026-04-01 01:38:09 (299 MB/s) - ‘physionet.org/files/ptb-xl/1.0.3/scp_statements.csv’ saved [9720/9720]

In [15]:
import sys
sys.path.append('.')
from pathlib import Path
import ast
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import wfdb
from sklearn.metrics import roc_auc_score, f1_score, classification_report

from ecg_ssl.model import ECGMaskedSSL
from ecg_ssl import config

In [16]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda

In [17]:
pretrained_model = ECGMaskedSSL(
    in_channels=config.IN_CHANNELS,
    seq_len=config.SEQ_LEN,
    d_model=config.D_MODEL,
    patch_size=config.PATCH_SIZE,
    num_heads=config.NUM_HEADS,
    num_layers=config.NUM_LAYERS,
    mlp_ratio=config.MLP_RATIO,
    dropout=config.DROPOUT,
).to(device)

checkpoint_path = Path("checkpoints_fixed_ssl_rawpatch/best.pt")
checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
pretrained_model.load_state_dict(checkpoint["model_state_dict"])
pretrained_model.eval()
print("loaded checkpoint from: ", checkpoint_path)

loaded checkpoint from:  checkpoints_fixed_ssl_rawpatch/best.pt

In [18]:
class PTBXLClassifier(nn.Module):
  def __init__(self, pretrained_model, feature_dim = 256, num_classes=1):
    super().__init__()
    self.pretrained_model = pretrained_model
    self.classifier = nn.Linear(feature_dim, num_classes)

  def forward(self, x):
    out = self.pretrained_model(x)
    pooled = out["pooled"]
    logits = self.classifier(pooled)
    return logits

In [19]:
model = PTBXLClassifier(pretrained_model).to(device)
print(model)

PTBXLClassifier(
  (pretrained_model): ECGMaskedSSL(
    (tokenizer): FixedCNNTokenizer(
      (proj): Conv1d(12, 256, kernel_size=(50,), stride=(50,))
    )
    (posenc): LearnablePositionalEncoding()
    (encoder): TransformerEncoder(
      (encoder): TransformerEncoder(
        (layers): ModuleList(
          (0-3): 4 x TransformerEncoderLayer(
            (self_attn): MultiheadAttention(
              (out_proj): NonDynamicallyQuantizableLinear(in_features=256, out_features=256, bias=True)
            )
            (linear1): Linear(in_features=256, out_features=1024, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
            (linear2): Linear(in_features=1024, out_features=256, bias=True)
            (norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            (norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            (dropout1): Dropout(p=0.1, inplace=False)
            (dropout2): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pred_head): Sequential(
      (0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (1): Linear(in_features=256, out_features=256, bias=True)
      (2): GELU(approximate='none')
      (3): Linear(in_features=256, out_features=600, bias=True)
    )
  )
  (classifier): Linear(in_features=256, out_features=1, bias=True)
)

In [20]:
ptbxl_path = Path("physionet.org/files/ptb-xl/1.0.3")

label_df = pd.read_csv(ptbxl_path / "ptbxl_database.csv")
scp_df = pd.read_csv(ptbxl_path / "scp_statements.csv", index_col=0)

print("label_df shape:", label_df.shape)
print("scp_df shape:", scp_df.shape)
display(label_df.head())
display(scp_df.head())

label_df shape: (21799, 28)
scp_df shape: (71, 12)

,ecg_id,patient_id,age,sex,height,weight,nurse,site,device,recording_date,...,validated_by_human,baseline_drift,static_noise,burst_noise,electrodes_problems,extra_beats,pacemaker,strat_fold,filename_lr,filename_hr
0,1,15709.0,56.0,1,NaN,63.0,2.0,0.0,CS-12 E,1984-11-09 09:17:34,...,True,NaN,", I-V1,",NaN,NaN,NaN,NaN,3,records100/00000/00001_lr,records500/00000/00001_hr
1,2,13243.0,19.0,0,NaN,70.0,2.0,0.0,CS-12 E,1984-11-14 12:55:37,...,True,NaN,NaN,NaN,NaN,NaN,NaN,2,records100/00000/00002_lr,records500/00000/00002_hr
2,3,20372.0,37.0,1,NaN,69.0,2.0,0.0,CS-12 E,1984-11-15 12:49:10,...,True,NaN,NaN,NaN,NaN,NaN,NaN,5,records100/00000/00003_lr,records500/00000/00003_hr
3,4,17014.0,24.0,0,NaN,82.0,2.0,0.0,CS-12 E,1984-11-15 13:44:57,...,True,", II,III,AVF",NaN,NaN,NaN,NaN,NaN,3,records100/00000/00004_lr,records500/00000/00004_hr
4,5,17448.0,19.0,1,NaN,70.0,2.0,0.0,CS-12 E,1984-11-17 10:43:15,...,True,", III,AVR,AVF",NaN,NaN,NaN,NaN,NaN,4,records100/00000/00005_lr,records500/00000/00005_hr

,description,diagnostic,form,rhythm,diagnostic_class,diagnostic_subclass,Statement Category,SCP-ECG Statement Description,AHA code,aECG REFID,CDISC Code,DICOM Code
NDT,non-diagnostic T abnormalities,1.0,1.0,NaN,STTC,STTC,other ST-T descriptive statements,non-diagnostic T abnormalities,NaN,NaN,NaN,NaN
NST_,non-specific ST changes,1.0,1.0,NaN,STTC,NST_,Basic roots for coding ST-T changes and abnorm...,non-specific ST changes,145.0,MDC_ECG_RHY_STHILOST,NaN,NaN
DIG,digitalis-effect,1.0,1.0,NaN,STTC,STTC,other ST-T descriptive statements,suggests digitalis-effect,205.0,NaN,NaN,NaN
LNGQT,long QT-interval,1.0,1.0,NaN,STTC,STTC,other ST-T descriptive statements,long QT-interval,148.0,NaN,NaN,NaN
NORM,normal ECG,1.0,NaN,NaN,NORM,NORM,Normal/abnormal,normal ECG,1.0,NaN,NaN,F-000B7

In [21]:
label_df["scp_codes"] = label_df["scp_codes"].apply(ast.literal_eval)
label_df[["scp_codes"]].head()

                                  scp_codes
0  {'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}
1              {'NORM': 80.0, 'SBRAD': 0.0}
2                {'NORM': 100.0, 'SR': 0.0}
3                {'NORM': 100.0, 'SR': 0.0}
4                {'NORM': 100.0, 'SR': 0.0}

In [22]:
def is_normal_ecg(code_dict):
    return int("NORM" in code_dict)

label_df["target_norm"] = label_df["scp_codes"].apply(is_normal_ecg)

print(label_df["target_norm"].value_counts())

target_norm
0    12285
1     9514
Name: count, dtype: int64

In [23]:
ptbxl_download_dir = "ptbxl_download"

sample_records = label_df["filename_hr"].head(500).tolist()

wfdb.dl_database(
    "ptb-xl",
    dl_dir=ptbxl_download_dir,
    records=sample_records,
)

print("Done")

Generating record list for: records500/00000/00001_hr
Generating record list for: records500/00000/00002_hr
Generating record list for: records500/00000/00003_hr
Generating record list for: records500/00000/00004_hr
Generating record list for: records500/00000/00005_hr
Generating record list for: records500/00000/00006_hr
Generating record list for: records500/00000/00007_hr
Generating record list for: records500/00000/00008_hr
Generating record list for: records500/00000/00009_hr
Generating record list for: records500/00000/00010_hr
Generating record list for: records500/00000/00011_hr
Generating record list for: records500/00000/00012_hr
Generating record list for: records500/00000/00013_hr
Generating record list for: records500/00000/00014_hr
Generating record list for: records500/00000/00015_hr
Generating record list for: records500/00000/00016_hr
Generating record list for: records500/00000/00017_hr
Generating record list for: records500/00000/00018_hr
Generating record list for: records500/00000/00019_hr
Generating record list for: records500/00000/00020_hr
Generating record list for: records500/00000/00021_hr
Generating record list for: records500/00000/00022_hr
Generating record list for: records500/00000/00023_hr
Generating record list for: records500/00000/00024_hr
Generating record list for: records500/00000/00025_hr
Generating record list for: records500/00000/00026_hr
Generating record list for: records500/00000/00027_hr
Generating record list for: records500/00000/00028_hr
Generating record list for: records500/00000/00029_hr
Generating record list for: records500/00000/00030_hr
Generating record list for: records500/00000/00031_hr
Generating record list for: records500/00000/00032_hr
Generating record list for: records500/00000/00033_hr
Generating record list for: records500/00000/00034_hr
Generating record list for: records500/00000/00035_hr
Generating record list for: records500/00000/00036_hr
Generating record list for: records500/00000/00037_hr
Generating record list for: records500/00000/00038_hr
Generating record list for: records500/00000/00039_hr
Generating record list for: records500/00000/00040_hr
Generating record list for: records500/00000/00041_hr
Generating record list for: records500/00000/00042_hr
Generating record list for: records500/00000/00043_hr
Generating record list for: records500/00000/00044_hr
Generating record list for: records500/00000/00045_hr
Generating record list for: records500/00000/00046_hr
Generating record list for: records500/00000/00047_hr
Generating record list for: records500/00000/00048_hr
Generating record list for: records500/00000/00049_hr
Generating record list for: records500/00000/00050_hr
Generating record list for: records500/00000/00051_hr
Generating record list for: records500/00000/00052_hr
Generating record list for: records500/00000/00053_hr
Generating record list for: records500/00000/00054_hr
Generating record list for: records500/00000/00055_hr
Generating record list for: records500/00000/00056_hr
Generating record list for: records500/00000/00057_hr
Generating record list for: records500/00000/00058_hr
Generating record list for: records500/00000/00059_hr
Generating record list for: records500/00000/00060_hr
Generating record list for: records500/00000/00061_hr
Generating record list for: records500/00000/00062_hr
Generating record list for: records500/00000/00063_hr
Generating record list for: records500/00000/00064_hr
Generating record list for: records500/00000/00065_hr
Generating record list for: records500/00000/00066_hr
Generating record list for: records500/00000/00067_hr
Generating record list for: records500/00000/00068_hr
Generating record list for: records500/00000/00069_hr
Generating record list for: records500/00000/00070_hr
Generating record list for: records500/00000/00071_hr
Generating record list for: records500/00000/00072_hr
Generating record list for: records500/00000/00073_hr
Generating record list for: records500/00000/00074_hr
Generating record list for: records500/00000/00075_hr
Generating record list for: records500/00000/00076_hr
Generating record list for: records500/00000/00077_hr
Generating record list for: records500/00000/00078_hr
Generating record list for: records500/00000/00079_hr
Generating record list for: records500/00000/00080_hr
Generating record list for: records500/00000/00081_hr
Generating record list for: records500/00000/00082_hr
Generating record list for: records500/00000/00083_hr
Generating record list for: records500/00000/00084_hr
Generating record list for: records500/00000/00085_hr
Generating record list for: records500/00000/00086_hr
Generating record list for: records500/00000/00087_hr
Generating record list for: records500/00000/00088_hr
Generating record list for: records500/00000/00089_hr
Generating record list for: records500/00000/00090_hr
Generating record list for: records500/00000/00091_hr
Generating record list for: records500/00000/00092_hr
Generating record list for: records500/00000/00093_hr
Generating record list for: records500/00000/00094_hr
Generating record list for: records500/00000/00095_hr
Generating record list for: records500/00000/00096_hr
Generating record list for: records500/00000/00097_hr
Generating record list for: records500/00000/00098_hr
Generating record list for: records500/00000/00099_hr
Generating record list for: records500/00000/00100_hr
Generating record list for: records500/00000/00101_hr
Generating record list for: records500/00000/00102_hr
Generating record list for: records500/00000/00103_hr
Generating record list for: records500/00000/00104_hr
Generating record list for: records500/00000/00105_hr
Generating record list for: records500/00000/00106_hr
Generating record list for: records500/00000/00107_hr
Generating record list for: records500/00000/00108_hr
Generating record list for: records500/00000/00109_hr
Generating record list for: records500/00000/00110_hr
Generating record list for: records500/00000/00111_hr
Generating record list for: records500/00000/00112_hr
Generating record list for: records500/00000/00113_hr
Generating record list for: records500/00000/00114_hr
Generating record list for: records500/00000/00115_hr
Generating record list for: records500/00000/00116_hr
Generating record list for: records500/00000/00117_hr
Generating record list for: records500/00000/00118_hr
Generating record list for: records500/00000/00119_hr
Generating record list for: records500/00000/00120_hr
Generating record list for: records500/00000/00121_hr
Generating record list for: records500/00000/00122_hr
Generating record list for: records500/00000/00123_hr
Generating record list for: records500/00000/00124_hr
Generating record list for: records500/00000/00125_hr
Generating record list for: records500/00000/00126_hr
Generating record list for: records500/00000/00127_hr
Generating record list for: records500/00000/00128_hr
Generating record list for: records500/00000/00129_hr
Generating record list for: records500/00000/00130_hr
Generating record list for: records500/00000/00131_hr
Generating record list for: records500/00000/00132_hr
Generating record list for: records500/00000/00133_hr
Generating record list for: records500/00000/00134_hr
Generating record list for: records500/00000/00135_hr
Generating record list for: records500/00000/00136_hr
Generating record list for: records500/00000/00138_hr
Generating record list for: records500/00000/00144_hr
Generating record list for: records500/00000/00146_hr
Generating record list for: records500/00000/00147_hr
Generating record list for: records500/00000/00148_hr
Generating record list for: records500/00000/00149_hr
Generating record list for: records500/00000/00150_hr
Generating record list for: records500/00000/00151_hr
Generating record list for: records500/00000/00152_hr
Generating record list for: records500/00000/00153_hr
Generating record list for: records500/00000/00154_hr
Generating record list for: records500/00000/00155_hr
Generating record list for: records500/00000/00156_hr
Generating record list for: records500/00000/00157_hr
Generating record list for: records500/00000/00158_hr
Generating record list for: records500/00000/00159_hr
Generating record list for: records500/00000/00160_hr
Generating record list for: records500/00000/00161_hr
Generating record list for: records500/00000/00162_hr
Generating record list for: records500/00000/00163_hr
Generating record list for: records500/00000/00164_hr
Generating record list for: records500/00000/00165_hr
Generating record list for: records500/00000/00166_hr
Generating record list for: records500/00000/00167_hr
Generating record list for: records500/00000/00168_hr
Generating record list for: records500/00000/00169_hr
Generating record list for: records500/00000/00170_hr
Generating record list for: records500/00000/00171_hr
Generating record list for: records500/00000/00172_hr
Generating record list for: records500/00000/00173_hr
Generating record list for: records500/00000/00174_hr
Generating record list for: records500/00000/00175_hr
Generating record list for: records500/00000/00176_hr
Generating record list for: records500/00000/00177_hr
Generating record list for: records500/00000/00178_hr
Generating record list for: records500/00000/00179_hr
Generating record list for: records500/00000/00180_hr
Generating record list for: records500/00000/00181_hr
Generating record list for: records500/00000/00182_hr
Generating record list for: records500/00000/00183_hr
Generating record list for: records500/00000/00184_hr
Generating record list for: records500/00000/00185_hr
Generating record list for: records500/00000/00186_hr
Generating record list for: records500/00000/00187_hr
Generating record list for: records500/00000/00188_hr
Generating record list for: records500/00000/00189_hr
Generating record list for: records500/00000/00190_hr
Generating record list for: records500/00000/00191_hr
Generating record list for: records500/00000/00192_hr
Generating record list for: records500/00000/00193_hr
Generating record list for: records500/00000/00194_hr
Generating record list for: records500/00000/00195_hr
Generating record list for: records500/00000/00196_hr
Generating record list for: records500/00000/00197_hr
Generating record list for: records500/00000/00198_hr
Generating record list for: records500/00000/00199_hr
Generating record list for: records500/00000/00200_hr
Generating record list for: records500/00000/00201_hr
Generating record list for: records500/00000/00202_hr
Generating record list for: records500/00000/00203_hr
Generating record list for: records500/00000/00204_hr
Generating record list for: records500/00000/00205_hr
Generating record list for: records500/00000/00206_hr
Generating record list for: records500/00000/00207_hr
Generating record list for: records500/00000/00208_hr
Generating record list for: records500/00000/00209_hr
Generating record list for: records500/00000/00210_hr
Generating record list for: records500/00000/00211_hr
Generating record list for: records500/00000/00212_hr
Generating record list for: records500/00000/00213_hr
Generating record list for: records500/00000/00214_hr
Generating record list for: records500/00000/00215_hr
Generating record list for: records500/00000/00216_hr
Generating record list for: records500/00000/00217_hr
Generating record list for: records500/00000/00218_hr
Generating record list for: records500/00000/00219_hr
Generating record list for: records500/00000/00220_hr
Generating record list for: records500/00000/00221_hr
Generating record list for: records500/00000/00222_hr
Generating record list for: records500/00000/00223_hr
Generating record list for: records500/00000/00224_hr
Generating record list for: records500/00000/00225_hr
Generating record list for: records500/00000/00226_hr
Generating record list for: records500/00000/00227_hr
Generating record list for: records500/00000/00228_hr
Generating record list for: records500/00000/00229_hr
Generating record list for: records500/00000/00230_hr
Generating record list for: records500/00000/00231_hr
Generating record list for: records500/00000/00232_hr
Generating record list for: records500/00000/00233_hr
Generating record list for: records500/00000/00234_hr
Generating record list for: records500/00000/00235_hr
Generating record list for: records500/00000/00236_hr
Generating record list for: records500/00000/00237_hr
Generating record list for: records500/00000/00238_hr
Generating record list for: records500/00000/00239_hr
Generating record list for: records500/00000/00240_hr
Generating record list for: records500/00000/00241_hr
Generating record list for: records500/00000/00242_hr
Generating record list for: records500/00000/00243_hr
Generating record list for: records500/00000/00244_hr
Generating record list for: records500/00000/00245_hr
Generating record list for: records500/00000/00246_hr
Generating record list for: records500/00000/00247_hr
Generating record list for: records500/00000/00248_hr
Generating record list for: records500/00000/00249_hr
Generating record list for: records500/00000/00250_hr
Generating record list for: records500/00000/00251_hr
Generating record list for: records500/00000/00252_hr
Generating record list for: records500/00000/00253_hr
Generating record list for: records500/00000/00254_hr
Generating record list for: records500/00000/00255_hr
Generating record list for: records500/00000/00256_hr
Generating record list for: records500/00000/00257_hr
Generating record list for: records500/00000/00258_hr
Generating record list for: records500/00000/00259_hr
Generating record list for: records500/00000/00260_hr
Generating record list for: records500/00000/00261_hr
Generating record list for: records500/00000/00262_hr
Generating record list for: records500/00000/00263_hr
Generating record list for: records500/00000/00264_hr
Generating record list for: records500/00000/00265_hr
Generating record list for: records500/00000/00266_hr
Generating record list for: records500/00000/00267_hr
Generating record list for: records500/00000/00268_hr
Generating record list for: records500/00000/00269_hr
Generating record list for: records500/00000/00270_hr
Generating record list for: records500/00000/00271_hr
Generating record list for: records500/00000/00272_hr
Generating record list for: records500/00000/00273_hr
Generating record list for: records500/00000/00274_hr
Generating record list for: records500/00000/00275_hr
Generating record list for: records500/00000/00276_hr
Generating record list for: records500/00000/00277_hr
Generating record list for: records500/00000/00278_hr
Generating record list for: records500/00000/00279_hr
Generating record list for: records500/00000/00280_hr
Generating record list for: records500/00000/00281_hr
Generating record list for: records500/00000/00282_hr
Generating record list for: records500/00000/00283_hr
Generating record list for: records500/00000/00284_hr
Generating record list for: records500/00000/00285_hr
Generating record list for: records500/00000/00286_hr
Generating record list for: records500/00000/00287_hr
Generating record list for: records500/00000/00288_hr
Generating record list for: records500/00000/00289_hr
Generating record list for: records500/00000/00290_hr
Generating record list for: records500/00000/00291_hr
Generating record list for: records500/00000/00292_hr
Generating record list for: records500/00000/00293_hr
Generating record list for: records500/00000/00294_hr
Generating record list for: records500/00000/00295_hr
Generating record list for: records500/00000/00296_hr
Generating record list for: records500/00000/00297_hr
Generating record list for: records500/00000/00298_hr
Generating record list for: records500/00000/00299_hr
Generating record list for: records500/00000/00300_hr
Generating record list for: records500/00000/00301_hr
Generating record list for: records500/00000/00302_hr
Generating record list for: records500/00000/00303_hr
Generating record list for: records500/00000/00304_hr
Generating record list for: records500/00000/00305_hr
Generating record list for: records500/00000/00306_hr
Generating record list for: records500/00000/00307_hr
Generating record list for: records500/00000/00308_hr
Generating record list for: records500/00000/00309_hr
Generating record list for: records500/00000/00310_hr
Generating record list for: records500/00000/00311_hr
Generating record list for: records500/00000/00312_hr
Generating record list for: records500/00000/00313_hr
Generating record list for: records500/00000/00314_hr
Generating record list for: records500/00000/00315_hr
Generating record list for: records500/00000/00316_hr
Generating record list for: records500/00000/00317_hr
Generating record list for: records500/00000/00318_hr
Generating record list for: records500/00000/00319_hr
Generating record list for: records500/00000/00320_hr
Generating record list for: records500/00000/00321_hr
Generating record list for: records500/00000/00322_hr
Generating record list for: records500/00000/00323_hr
Generating record list for: records500/00000/00324_hr
Generating record list for: records500/00000/00325_hr
Generating record list for: records500/00000/00326_hr
Generating record list for: records500/00000/00327_hr
Generating record list for: records500/00000/00328_hr
Generating record list for: records500/00000/00329_hr
Generating record list for: records500/00000/00330_hr
Generating record list for: records500/00000/00331_hr
Generating record list for: records500/00000/00332_hr
Generating record list for: records500/00000/00333_hr
Generating record list for: records500/00000/00334_hr
Generating record list for: records500/00000/00335_hr
Generating record list for: records500/00000/00336_hr
Generating record list for: records500/00000/00337_hr
Generating record list for: records500/00000/00338_hr
Generating record list for: records500/00000/00339_hr
Generating record list for: records500/00000/00340_hr
Generating record list for: records500/00000/00341_hr
Generating record list for: records500/00000/00342_hr
Generating record list for: records500/00000/00343_hr
Generating record list for: records500/00000/00344_hr
Generating record list for: records500/00000/00345_hr
Generating record list for: records500/00000/00346_hr
Generating record list for: records500/00000/00347_hr
Generating record list for: records500/00000/00348_hr
Generating record list for: records500/00000/00349_hr
Generating record list for: records500/00000/00350_hr
Generating record list for: records500/00000/00351_hr
Generating record list for: records500/00000/00352_hr
Generating record list for: records500/00000/00353_hr
Generating record list for: records500/00000/00354_hr
Generating record list for: records500/00000/00355_hr
Generating record list for: records500/00000/00356_hr
Generating record list for: records500/00000/00357_hr
Generating record list for: records500/00000/00358_hr
Generating record list for: records500/00000/00359_hr
Generating record list for: records500/00000/00360_hr
Generating record list for: records500/00000/00361_hr
Generating record list for: records500/00000/00362_hr
Generating record list for: records500/00000/00363_hr
Generating record list for: records500/00000/00364_hr
Generating record list for: records500/00000/00365_hr
Generating record list for: records500/00000/00366_hr
Generating record list for: records500/00000/00367_hr
Generating record list for: records500/00000/00368_hr
Generating record list for: records500/00000/00369_hr
Generating record list for: records500/00000/00370_hr
Generating record list for: records500/00000/00371_hr
Generating record list for: records500/00000/00372_hr
Generating record list for: records500/00000/00373_hr
Generating record list for: records500/00000/00374_hr
Generating record list for: records500/00000/00375_hr
Generating record list for: records500/00000/00376_hr
Generating record list for: records500/00000/00377_hr

In [24]:
!find ptbxl_download -name "*_hr.hea" | wc -l
!find ptbxl_download -name "*_hr.dat" | wc -l

500
500

In [25]:
ptbxl_path = Path("ptbxl_download")

In [26]:
def get_ecg_path_hr(row):
    return ptbxl_path / row["filename_hr"]

label_df["ecg_path"] = label_df.apply(get_ecg_path_hr, axis=1)

def files_exist(row):
    base = Path(row["ecg_path"])
    return Path(str(base) + ".hea").exists() and Path(str(base) + ".dat").exists()

label_df["file_exists"] = label_df.apply(files_exist, axis=1)
print(label_df["file_exists"].value_counts())

file_exists
False    21299
True       500
Name: count, dtype: int64

In [27]:
label_df_small = label_df[label_df["file_exists"]].copy()

print("Remaining rows:", len(label_df_small))
print(label_df_small["target_norm"].value_counts())

Remaining rows: 500
target_norm
1    297
0    203
Name: count, dtype: int64

In [28]:
class PTBXLDataset(Dataset):
    def __init__(self, df):
        self.df = df.reset_index(drop=True)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        record_path = str(row["ecg_path"])

        record = wfdb.rdrecord(record_path)
        x = record.p_signal.astype(np.float32).T   # (12, 5000)

        mean = x.mean(axis=1, keepdims=True)
        std = x.std(axis=1, keepdims=True)
        x = (x - mean) / np.clip(std, 1e-4, None)
        x = np.clip(x, -5, 5)

        x = torch.from_numpy(x).float()
        y = torch.tensor(row["target_norm"], dtype=torch.float32)

        return x, y

In [29]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    label_df_small,
    test_size=0.30,
    random_state=42,
    stratify=label_df_small["target_norm"],
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42,
    stratify=None,
)

print("Train:", len(train_df))
print("Val:", len(val_df))
print("Test:", len(test_df))

print("\nTrain label counts:")
print(train_df["target_norm"].value_counts())

print("\nVal label counts:")
print(val_df["target_norm"].value_counts())

print("\nTest label counts:")
print(test_df["target_norm"].value_counts())

Train: 350
Val: 75
Test: 75

In [30]:
train_dataset = PTBXLDataset(train_df)
val_dataset = PTBXLDataset(val_df)
test_dataset = PTBXLDataset(test_df)

batch_size = 8

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0)

print("Dataloaders ready")

Dataloaders ready

In [37]:
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=2e-5, weight_decay=.05)

In [38]:
def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss = 0.0

    for x, y in loader:
        x = x.to(device)
        y = y.to(device).unsqueeze(1)

        optimizer.zero_grad()
        logits = model(x)
        loss = criterion(logits, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)

In [39]:
def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss = 0.0
    all_probs = []
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for x, y in loader:
            x = x.to(device)
            y = y.to(device).unsqueeze(1)

            logits = model(x)
            loss = criterion(logits, y)
            probs = torch.sigmoid(logits)
            preds = (probs > 0.5).float()

            total_loss += loss.item()
            all_probs.extend(probs.cpu().numpy().flatten())
            all_preds.extend(preds.cpu().numpy().flatten())
            all_labels.extend(y.cpu().numpy().flatten())

    auc = roc_auc_score(all_labels, all_probs)
    f1 = f1_score(all_labels, all_preds)

    return total_loss / len(loader), auc, f1

In [40]:
num_epochs = 3

for epoch in range(num_epochs):
    train_loss = train_one_epoch(model, train_loader, optimizer, criterion, device)
    val_loss, val_auc, val_f1 = evaluate(model, val_loader, criterion, device)

    print(f"Epoch {epoch+1}/{num_epochs}")
    print(f"Train Loss: {train_loss:.4f}")
    print(f"Val Loss:   {val_loss:.4f}")
    print(f"Val AUC:    {val_auc:.4f}")
    print(f"Val F1:     {val_f1:.4f}")
    print("-" * 40)

Epoch 1/3
Train Loss: 0.2816
Val Loss:   0.4803
Val AUC:    0.8644
Val F1:     0.7907
----------------------------------------
Epoch 2/3
Train Loss: 0.2773
Val Loss:   0.4582
Val AUC:    0.8615
Val F1:     0.8571
----------------------------------------
Epoch 3/3
Train Loss: 0.2479
Val Loss:   0.4933
Val AUC:    0.8452
Val F1:     0.8602
----------------------------------------

In [41]:
test_loss, test_auc, test_f1 = evaluate(model, test_loader, criterion, device)

print("Test Loss:", round(test_loss, 4))
print("Test AUC:", round(test_auc, 4))
print("Test F1:", round(test_f1, 4))

Test Loss: 0.4852
Test AUC: 0.8695
Test F1: 0.8132

References to remember for report, we can delete this at the end I just dont want to forget

Goldberger, A., Amaral, L., Glass, L., Hausdorff, J., Ivanov, P. C., Mark, R., ... & Stanley, H. E. (2000). PhysioBank, PhysioToolkit, and PhysioNet: Components of a new research resource for complex physiologic signals. Circulation [Online]. 101 (23), pp. e215–e220. RRID:SCR_007345.


Wagner, P., Strodthoff, N., Bousseljot, R., Samek, W., & Schaeffter, T. (2022). PTB-XL, a large publicly available electrocardiography dataset (version 1.0.3). PhysioNet. RRID:SCR_007345. https://doi.org/10.13026/kfzx-aw45


Wagner, P., Strodthoff, N., Bousseljot, R.-D., Kreiseler, D., Lunze, F.I., Samek, W., Schaeffter, T. (2020), PTB-XL: A Large Publicly Available ECG Dataset. Scientific Data. https://doi.org/10.1038/s41597-020-0495-6